import { resolve } from 'node:path';
import { defineConfig } from 'vite';
import react from '@vitejs/plugin-react';
import { ALL_PAGES, pageHtmlFile, pagePath } from './src/i18n/routes.js';

const root = import.meta.dirname;

/** Clean URLs (e.g. /en, /contact, /en/terms) of every page except the root. */
const PAGE_PATHS = new Set(ALL_PAGES.map(({ id, locale }) => pagePath(id, locale)).filter((path) => path !== '/'));

/**
 * Serves each page at its clean URL (no trailing slash) in dev and preview,
 * matching how static hosts resolve the built `<path>/index.html`.
 */
function cleanPageUrls() {
  const rewrite = (req, _res, next) => {
    const [path, query] = req.url.split('?');
    if (PAGE_PATHS.has(path)) {
      req.url = `${path}/${query ? `?${query}` : ''}`;
    }
    next();
  };
  // Hooks must not return a value: Vite would treat it as a post-middleware hook.
  return {
    name: 'tjar-clean-page-urls',
    configureServer(server) {
      server.middlewares.use(rewrite);
    },
    configurePreviewServer(server) {
      server.middlewares.use(rewrite);
    },
  };
}

/** Long-term cacheable vendor chunks. */
function manualChunks(id) {
  // Vite normalises module ids to forward slashes on every OS.
  if (/\/node_modules\/(framer-motion|motion-dom|motion-utils)\//.test(id)) return 'motion';
  if (/\/node_modules\/(react|react-dom|scheduler)\//.test(id)) return 'react';
  return undefined;
}

export default defineConfig({
  plugins: [react(), cleanPageUrls()],
  build: {
    // Screenshots are tiny WebP files; keep them as hashed, cacheable files.
    assetsInlineLimit: 0,
    rollupOptions: {
      // Static multi-page build: one real HTML page per page and language
      // (generated by scripts/generate-pages.mjs), so every URL works on any
      // static host without rewrite rules and ships complete SEO markup.
      input: Object.fromEntries(
        ALL_PAGES.map(({ id, locale }) => [`${locale}-${id}`, resolve(root, pageHtmlFile(id, locale))]),
      ),
      output: { manualChunks },
    },
  },
});
