import { SITE_URL } from '../config/site';

/**
 * robots.txt, generated by the Next.js Metadata API instead of the old
 * hand-rolled public/robots.txt. The site is fully crawlable.
 */
export const dynamic = 'force-static';

export default function robots() {
  return {
    rules: [{ userAgent: '*', allow: '/' }],
    sitemap: new URL('/sitemap.xml', `${SITE_URL}/`).href,
    host: SITE_URL,
  };
}
