import { DEFAULT_LOCALE, LOCALE_CODES } from '../i18n/locales';
import { ALL_PAGES, pagePath } from '../i18n/routes';
import { SITE_URL } from '../config/site';

/**
 * sitemap.xml, generated by the Next.js Metadata API instead of the old
 * hand-rolled public/sitemap.xml. Every URL carries hreflang alternates so
 * the Arabic and English versions of a page are linked in both directions.
 */
export const dynamic = 'force-static';

const TODAY = new Date().toISOString().slice(0, 10);

export default function sitemap() {
  const absolute = (path) => new URL(path, `${SITE_URL}/`).href;

  return ALL_PAGES.map(({ id, locale }) => {
    const languages = Object.fromEntries(LOCALE_CODES.map((code) => [code, absolute(pagePath(id, code))]));

    return {
      url: absolute(pagePath(id, locale)),
      lastModified: TODAY,
      changeFrequency: id === 'home' ? 'weekly' : 'monthly',
      priority: id === 'home' ? 1 : 0.6,
      alternates: { languages: { ...languages, 'x-default': absolute(pagePath(id, DEFAULT_LOCALE)) } },
    };
  });
}
