/**
 * Generates the static HTML entry for every page in every language, plus
 * sitemap.xml and robots.txt — so crawlers get complete, localized SEO
 * without running JavaScript.
 *
 * Sources of truth:
 *   src/i18n/routes.js        pages and URLs
 *   src/i18n/locales.js       languages (lang, dir, og:locale)
 *   src/content/<locale>/     titles, descriptions, FAQ (structured data)
 *   src/config/site.js        SITE_URL and contact details
 *
 * Runs automatically before `npm run dev` and `npm run build`.
 * The generated *.html files should not be edited by hand.
 */
import { mkdirSync, writeFileSync } from 'node:fs';
import { dirname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';
import { SITE_URL, contact } from '../src/config/site.js';
import ar from '../src/content/ar/index.js';
import en from '../src/content/en/index.js';
import { DEFAULT_LOCALE, LOCALE_CODES, LOCALES } from '../src/i18n/locales.js';
import { ALL_PAGES, pageHtmlFile, pagePath } from '../src/i18n/routes.js';

const ROOT = resolve(dirname(fileURLToPath(import.meta.url)), '..');
const DICTIONARIES = { ar, en };
const ENTRIES = { home: 'home', contact: 'contact', privacy: 'privacy', terms: 'terms' };
const THEME_COLOR = '#00A5A5';
const TODAY = new Date().toISOString().slice(0, 10);

const absolute = (path) => new URL(path, `${SITE_URL}/`).href;

const escapeHtml = (value) =>
  String(value).replace(/[&<>"']/g, (char) => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', '"': '&quot;', "'": '&#39;' })[char]);

/** Page heading used in breadcrumbs (the meta title carries the brand suffix). */
function pageHeading(pageId, t) {
  if (pageId === 'contact') return t.contactPage.title;
  if (pageId === 'privacy' || pageId === 'terms') return t.legal[pageId].title;
  return t.common.home;
}

function structuredData(pageId, locale, t, url) {
  const meta = t.meta.pages[pageId];
  const organization = {
    '@type': 'Organization',
    '@id': `${SITE_URL}/#organization`,
    name: 'TJAR',
    alternateName: ['تي جار', 'T Jar'],
    url: absolute('/'),
    logo: { '@type': 'ImageObject', url: absolute('/icon-512.png'), width: 512, height: 512 },
    email: contact.email,
    contactPoint: {
      '@type': 'ContactPoint',
      telephone: `+${contact.whatsappNumber}`,
      email: contact.email,
      contactType: 'customer support',
      availableLanguage: ['Arabic', 'English'],
    },
  };
  const website = {
    '@type': 'WebSite',
    '@id': `${SITE_URL}/#website`,
    url: absolute('/'),
    name: 'TJAR',
    alternateName: 'تي جار',
    inLanguage: LOCALE_CODES,
    publisher: { '@id': organization['@id'] },
  };
  const webpage = {
    '@type': pageId === 'contact' ? 'ContactPage' : 'WebPage',
    '@id': `${url}#webpage`,
    url,
    name: meta.title,
    description: meta.description,
    inLanguage: locale,
    isPartOf: { '@id': website['@id'] },
    about: { '@id': organization['@id'] },
    primaryImageOfPage: absolute(t.meta.ogImage),
  };
  const graph = [organization, website, webpage];

  if (pageId === 'home') {
    graph.push({
      '@type': 'FAQPage',
      '@id': `${url}#faq`,
      inLanguage: locale,
      mainEntity: t.home.faq.items.map((item) => ({
        '@type': 'Question',
        name: item.question,
        acceptedAnswer: { '@type': 'Answer', text: item.answer },
      })),
    });
  } else {
    const breadcrumb = {
      '@type': 'BreadcrumbList',
      '@id': `${url}#breadcrumb`,
      itemListElement: [
        { '@type': 'ListItem', position: 1, name: t.common.home, item: absolute(pagePath('home', locale)) },
        { '@type': 'ListItem', position: 2, name: pageHeading(pageId, t), item: url },
      ],
    };
    webpage.breadcrumb = { '@id': breadcrumb['@id'] };
    graph.push(breadcrumb);
  }

  // Escape "<" so the JSON can never close the script tag.
  return JSON.stringify({ '@context': 'https://schema.org', '@graph': graph }).replace(/</g, '\\u003c');
}

function renderHtml(pageId, locale) {
  const t = DICTIONARIES[locale];
  const { dir, ogLocale } = LOCALES[locale];
  const meta = t.meta.pages[pageId];
  const url = absolute(pagePath(pageId, locale));
  const ogImage = absolute(t.meta.ogImage);
  const title = escapeHtml(meta.title);
  const description = escapeHtml(meta.description);

  const alternates = [
    ...LOCALE_CODES.map((code) => [code, absolute(pagePath(pageId, code))]),
    ['x-default', absolute(pagePath(pageId, DEFAULT_LOCALE))],
  ]
    .map(([hreflang, href]) => `    <link rel="alternate" hreflang="${hreflang}" href="${href}" />`)
    .join('\n');

  const ogAlternates = LOCALE_CODES.filter((code) => code !== locale)
    .map((code) => `    <meta property="og:locale:alternate" content="${LOCALES[code].ogLocale}" />`)
    .join('\n');

  return `<!doctype html>
<!-- Generated by scripts/generate-pages.mjs. Edit src/content/${locale}/ui.js (meta) or the script, not this file. -->
<html lang="${locale}" dir="${dir}">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1, viewport-fit=cover" />
    <title>${title}</title>
    <meta name="description" content="${description}" />
    <meta name="robots" content="index, follow, max-image-preview:large" />
    <link rel="canonical" href="${url}" />
${alternates}

    <meta name="theme-color" content="${THEME_COLOR}" />
    <meta name="color-scheme" content="light" />
    <meta name="format-detection" content="telephone=no" />
    <link rel="icon" href="/favicon.svg" type="image/svg+xml" />
    <link rel="apple-touch-icon" href="/apple-touch-icon.png" />

    <meta property="og:type" content="website" />
    <meta property="og:site_name" content="${escapeHtml(t.meta.siteName)}" />
    <meta property="og:locale" content="${ogLocale}" />
${ogAlternates}
    <meta property="og:url" content="${url}" />
    <meta property="og:title" content="${title}" />
    <meta property="og:description" content="${description}" />
    <meta property="og:image" content="${ogImage}" />
    <meta property="og:image:type" content="image/jpeg" />
    <meta property="og:image:width" content="1200" />
    <meta property="og:image:height" content="630" />
    <meta property="og:image:alt" content="${escapeHtml(t.meta.ogImageAlt)}" />
    <meta name="twitter:card" content="summary_large_image" />
    <meta name="twitter:title" content="${title}" />
    <meta name="twitter:description" content="${description}" />
    <meta name="twitter:image" content="${ogImage}" />
    <meta name="twitter:image:alt" content="${escapeHtml(t.meta.ogImageAlt)}" />

    <script type="application/ld+json">${structuredData(pageId, locale, t, url)}</script>
  </head>
  <body>
    <div id="root"></div>
    <noscript>
      <p style="padding: 24px; font-family: system-ui, sans-serif">${escapeHtml(t.brand.tagline)}</p>
    </noscript>
    <script type="module" src="/src/entries/${ENTRIES[pageId]}.jsx"></script>
  </body>
</html>
`;
}

function renderSitemap() {
  const pageIds = [...new Set(ALL_PAGES.map((page) => page.id))];
  const urls = pageIds.flatMap((pageId) =>
    LOCALE_CODES.map((locale) => {
      const links = [
        ...LOCALE_CODES.map((code) => [code, absolute(pagePath(pageId, code))]),
        ['x-default', absolute(pagePath(pageId, DEFAULT_LOCALE))],
      ]
        .map(([hreflang, href]) => `    <xhtml:link rel="alternate" hreflang="${hreflang}" href="${href}" />`)
        .join('\n');
      return `  <url>
    <loc>${absolute(pagePath(pageId, locale))}</loc>
${links}
    <lastmod>${TODAY}</lastmod>
    <changefreq>${pageId === 'home' ? 'weekly' : 'monthly'}</changefreq>
    <priority>${pageId === 'home' ? '1.0' : '0.6'}</priority>
  </url>`;
    }),
  );

  return `<?xml version="1.0" encoding="UTF-8"?>
<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9" xmlns:xhtml="http://www.w3.org/1999/xhtml">
${urls.join('\n')}
</urlset>
`;
}

const robots = `User-agent: *
Allow: /

Sitemap: ${absolute('/sitemap.xml')}
`;

function write(relativePath, content) {
  const target = resolve(ROOT, relativePath);
  mkdirSync(dirname(target), { recursive: true });
  writeFileSync(target, content, 'utf8');
}

for (const { id, locale } of ALL_PAGES) write(pageHtmlFile(id, locale), renderHtml(id, locale));
write('public/sitemap.xml', renderSitemap());
write('public/robots.txt', robots);

console.log(`[pages] ${ALL_PAGES.length} HTML pages, sitemap.xml and robots.txt generated for ${SITE_URL}`);
